require('plugins')
require('options')
require('tree-config')
require('lualine-config')
require('treesitter-config')
require('autopairs-config')
require('lsp')
require('colorizer-config')
vim.cmd('colorscheme nord')
