require('plugins')
require('options')
require('tree-config')
require('lualine-config')
require('treesitter-config')
require('autopairs-config')
require('lsp')
require('colorizer-config')
require('comments-config')
require('floaterm-config')
require('null-ls-config')
require('prettier-config')
require('trouble-config')
vim.cmd('colorscheme nord')
