local o = vim.o
local g = vim.g
local opt = vim.opt
local wo = vim.wo
local bo = vim.bo

vim.cmd('filetype plugin indent on')
o.shortmess = o.shortmess .. 'c'
g.mapleader = ','
o.timeoutlen = 1000
o.hidden = true
o.whichwrap = 'b,s,<,>,[,],h,l'
o.pumheight = 10
o.fileencoding = 'utf-8'
o.cmdheight = 2
o.splitbelow = true
o.splitright = true
opt.termguicolors = true
o.conceallevel = 0
o.showmode = false
o.backup = false
o.writebackup = false
o.updatetime = 300
o.clipboard = 'unnamedplus'
o.hlsearch = false
o.ignorecase = true
o.scrolloff = 3
o.sidescrolloff = 5
wo.wrap = false
wo.number = true
wo.relativenumber = true
o.cursorline = true
o.signcolumn = "yes"
o.tabstop = 4
bo.tabstop = 4
o.softtabstop = 4
o.shiftwidth = 4
bo.shiftwidth = 4
o.autoindent = true
bo.autoindent = true
o.expandtab = true
o.smartindent = true
bo.expandtab = true
